apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    run: countries-assembly
  name: countries-assembly
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    run: countries-assembly
  type: LoadBalancer
status:
  loadBalancer: {}
